# This is the default setting for the SimCLR algorithm.
# Basic Settings
- epochs: 100
- start_epoch: 0
- batch_size: 256
- widening: 1

# Anything Optimizer
- optimizer: 'SGD'
- lr: 1e-2
- weight_decay: 0
- eps: 1e-08

# Dataset Settings
- dataset_name: 'CIFAR10'
- n_classes: 10

# SimCLR Settings
- augmentations: 2 # How many image augmentations are created and learned
- resize: 224 # Resize the image to this size
- projection_dim: 64 # Projection dimension for the linear classifier used by SimCLR
- temperature: 0.5 # Temperature is used for the similarity function

# Additional Settings
# - resume: False # Continue from a previous checkpoint. Note: A checkpoint file needs to be given.
- seed: 42 # Seed for numpy and torch
- save_every_epoch: 10 # Save the current state of the model after each nth Epoch

# Hugging Face
# IMPORTANT: Don't store your Hugging Face Token in any file and upload it. Rather use env variable HF_TOKEN
- HF_TOKEN: NULL

# Distributed Computation Settings
- dataset_workers: 8

# Gradient accumulation
- ga: False
- ga_count: 8

# Evaluation during Training
- eval_every: 5